services:
  - type: web
    name: cwl-war-council
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
    env: node
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - clashwarcouncil.com 